### ISSUE TITLE
infinite loop occurs

### ISSUE THREAD

**Issue by jehkael** [Lightman314/Lightmans-Discord-Integration#18]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-08-13 13:14:20
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.blockentity.CapabilityInterfaceBlockEntity.getCapability(CapabilityInterfaceBlockEntity.java:28) ~[lightmanscurrency-1.19.2-2.1.0.0d.jar%23377!/:1.19.2-2.1.0.0d] {re:classloading}
	at 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

	Crash Report UUID: 047596f8-e856-4131-be78-364ab2cc274c
	FML: 43.2
	Forge: net.minecraftforge:43.2.8

**Comment by Lightman314** [comment]
This is a Lightman's Currency issue, not a Lightman's Discord issue. Please report this on the [correct issue page](https://github.com/Lightman314/LightmansCurrency/issues).

Also, please attach the crash report to youer message (drag and drop the file into the text input) instead of copy/pasting a small portion of it. The entire issue context is necessary, and it's a pain to have to scroll past 100 lines of text to respond.
