### ISSUE TITLE
Incompatibility with ValkyrienSkies Mod

### ISSUE THREAD

**Issue by Waterspark63** [Lightman314/Lightmans-Discord-Integration#19]
When you have both ValkyrienSkies, and Lightman's Discord installed, because both of them are providing 'com.fasterxml.jackson.core', which causes the following crash (The 'issue' mod changes with every single load, but looking at the mod files, I figured out it was VS that was incompatible):

Forge: 40.2.10
Lightman's discord version: 1.18-2.0.0, Lightman's Currency: 1.18.2-2.1.2.2, LCTech: 1.18.2-0.2.0.0, VS: 1.18-2.1.0-Beta-14
```
Exception in thread "main" java.lang.module.ResolutionException: Modules lightmansdiscord and com.fasterxml.jackson.core export package com.fasterxml.jackson.core to module minecraft
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

Is there any possibility of getting these two to play together nicely? I'll also be putting this exact issue on VS's github and link it here.

**Comment by Lightman314** [comment]
Working on an update for LDI, and this should get fixed when it comes out :)

**Comment by Lightman314** [comment]
Should be fixed in LDI v0.2.0.1, as it now uses proper Jar-in-Jar libraries.

**Comment by Waterspark63** [comment]
Stupid question, is that a 'it's fixed in v0.2.0.1, and it's released', or a 'it will be fixed in v0.2.0.1 when released'? The second message made it sound as if it came out, but I'm not seeing it on curseforge ^^ Sorry if I'm misunderstanding.

**Comment by Lightman314** [comment]
It's fixed in 0.2.0.1, and it's released, but curseforge is taking ages to approve the new files...
Sadly there's not much I can do about that, but it is also available on Modrinth [here](https://modrinth.com/mod/ldi/versions) if you'd like an alternate download link.

**Comment by Waterspark63** [comment]
Unfortunately, it seems like it's still breaking something, I have this now:
```
Exception in thread "main" java.lang.module.ResolutionException: Modules thedarkcolour.kotlinforforge and kotlin.stdlib export package kotlin.reflect to module blockui
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```
        
And I believe it's still LDI, as when the mod is disabled, it works perfectly, but errors similar to the above when it's loaded.

**Comment by Lightman314** [comment]
It looks like it's technically conflicting with kotlin for forge now, which makes sense as I included kotlin in my jar as the JDA requires it to work. I'll see if I can make it use kotlin for forge instead of including kotlin manually.

**Comment by Lightman314** [comment]
Tested and now compatible with Kotlin for Forge in v0.2.0.2. As a downside, LDI now *requires* Kotlin for Forge, but that's a price I'm willing to pay.

Gonna leave the ticket open for now until I receive confirmation from you though. That said, Curseforge is still being stupid about approving the files so you'll likely need to download from Modrinth again...

**Comment by Waterspark63** [comment]
It seems to be working now! Thank you for the help! I'll let you know if anything else comes up. (I don't quite remember, are emotes meant to be converted on either side (If you have emojiful, and have a emote :beans:, and on the discord server you have a :beans: emote), should they convert to the emote, or no?)
