### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by mcenderdragon** [Lightman314/Lightmans-Discord-Integration#2]
Permission problems kills the serve ron startup. The bot has rolles to give him all needed permissions btu it still fails:
Forge 40.0.36
Minecraft 1.18.2
LDI : 0.0.3.1

```
[04Apr.2022 17:39:34.355] [Server thread/INFO] [io.github.lightman314.lightmansconsole.LightmansDiscordIntegration/]: Attempting to build the JDA.
[04Apr.2022 17:39:35.027] [Server thread/INFO] [io.github.lightman314.lightmansconsole.LightmansDiscordIntegration/]: Waiting for the JDA to finish the log in process.
[04Apr.2022 17:39:35.794] [Server thread/INFO] [io.github.lightman314.lightmansconsole.LightmansDiscordIntegration/]: JDA has successfully logged in.
[04Apr.2022 17:39:35.803] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class io.github.lightman314.lightmansconsole.discord.listeners.ListenerRegistration onJDAInit(Lio/github/lightman314/lightmansconsole/events/JDAInitializedEvent;)V
net.dv8tion.jda.api.exceptions.MissingAccessException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkAccess(AbstractChannelImpl.java:314)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:323)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:347)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.util.MessageUtil.lambda$sendTextMessage$0(MessageUtil.java:26)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.util.MessageUtil.sendTextMessage(MessageUtil.java:24)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.types.SingleChannelListener.sendTextMessage(SingleChannelListener.java:54)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.console.ConsoleMessageListener.<init>(ConsoleMessageListener.java:36)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.ListenerRegistration.onJDAInit(ListenerRegistration.java:22)
	at net.minecraftforge.eventbus.ASMEventHandler_4_ListenerRegistration_onJDAInit_JDAInitializedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.LightmansDiscordIntegration.onConfigLoad(LightmansDiscordIntegration.java:67)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.0.36/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:91)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:76)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:64)
	at TRANSFORMER/forge@40.0.36/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:171)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[04Apr.2022 17:39:35.808] [Server thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4030/0x00000008015ac650@9520d03
net.dv8tion.jda.api.exceptions.MissingAccessException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkAccess(AbstractChannelImpl.java:314)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:323)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:347)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.util.MessageUtil.lambda$sendTextMessage$0(MessageUtil.java:26)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.util.MessageUtil.sendTextMessage(MessageUtil.java:24)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.types.SingleChannelListener.sendTextMessage(SingleChannelListener.java:54)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.console.ConsoleMessageListener.<init>(ConsoleMessageListener.java:36)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.discord.listeners.ListenerRegistration.onJDAInit(ListenerRegistration.java:22)
	at net.minecraftforge.eventbus.ASMEventHandler_4_ListenerRegistration_onJDAInit_JDAInitializedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/lightmansdiscord@1.18-0.0.3.1/io.github.lightman314.lightmansconsole.LightmansDiscordIntegration.onConfigLoad(LightmansDiscordIntegration.java:67)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.0.36/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:91)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:76)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.18.2-40.0.36/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:64)
	at TRANSFORMER/forge@40.0.36/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:171)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[04Apr.2022 17:39:35.814] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.dv8tion.jda.api.exceptions.MissingAccessException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkAccess(AbstractChannelImpl.java:314) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:323) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:347) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at io.github.lightman314.lightmansconsole.util.MessageUtil.lambda$sendTextMessage$0(MessageUtil.java:26) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at io.github.lightman314.lightmansconsole.util.MessageUtil.sendTextMessage(MessageUtil.java:24) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at io.github.lightman314.lightmansconsole.discord.listeners.types.SingleChannelListener.sendTextMessage(SingleChannelListener.java:54) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at io.github.lightman314.lightmansconsole.discord.listeners.console.ConsoleMessageListener.<init>(ConsoleMessageListener.java:36) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at io.github.lightman314.lightmansconsole.discord.listeners.ListenerRegistration.onJDAInit(ListenerRegistration.java:22) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at net.minecraftforge.eventbus.ASMEventHandler_4_ListenerRegistration_onJDAInit_JDAInitializedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at io.github.lightman314.lightmansconsole.LightmansDiscordIntegration.onConfigLoad(LightmansDiscordIntegration.java:67) ~[lightmansdiscord-1.18-0.0.3.1-server.jar%2339!/:1.18-0.0.3.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55) ~[javafmllanguage-1.18.2-40.0.36.jar%2343!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:91) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:76) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:64) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:64) ~[fmlcore-1.18.2-40.0.36.jar%2342!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81) ~[forge-1.18.2-40.0.36-universal.jar%2345!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:171) ~[server-1.18.2-20220228.144236-srg.jar%2341!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.18.2-20220228.144236-srg.jar%2341!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220228.144236-srg.jar%2341!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Lightman314** [comment]
It would appear that despite thinking that you have permissions set up, you do not. I would retry the setup process from the beginning, making sure you have given the bot admin permissions on the Oauth2 URL Generator invite like so:
![image](https://user-images.githubusercontent.com/4554273/164260913-4cd23196-ab5a-4d61-822c-c157ebc367ea.png)

Also, make sure you have enabled the **Presence Intent** and the **Server Members Intent** as well.
![image](https://user-images.githubusercontent.com/4554273/164261071-707cee95-8e86-4fc1-8150-2de3882ed0b3.png)

I'm afraid anything more than that I cannot help you with, as permissions are all handled by discord and the JDA, and I am thusly unable to edit their code or manually give the bot permissions in the mod itself. I'll throw in some error catches so that stuff like this doesn't crash the server, but I'm afraid that's all that I can on my end.

**Comment by mcenderdragon** [comment]
I switched to a different mod and there it worked without changing anything, so i doubt its a permission problem. Also the view channel permission is definetly set ( rather i cant disable it) - is it possible to add more log ouput for what channel it failed?
