### ISSUE TITLE
Console error spam [Server]

### ISSUE THREAD

**Issue by atpoe** [Lightman314/Lightmans-Discord-Integration#20]
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "io.github.lightman314.lightmansdiscord.api.jda.data.SafeUserReference.isBot()" because "user" is null
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/io.github.lightman314.lightmansdiscord.discord.listeners.account.AccountMessageListener.OnMessage(AccountMessageListener.java:48)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/io.github.lightman314.lightmansdiscord.api.jda.listeners.SafeMultiChannelListener.onMessageReceived(SafeMultiChannelListener.java:67)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:442)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:176)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:136)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1014)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:900)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:878)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1053)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
at TRANSFORMER/lightmansdiscord@1.20-0.2.0.0/ldishadow.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by Lightman314** [comment]
Should no longer spam the logs in LDI v0.2.0.1.
