### ISSUE TITLE
Console error when starting up server

### ISSUE THREAD

**Issue by polenball** [Lightman314/Lightmans-Discord-Integration#23]
[Server thread/ERROR] [io.gi.li.li.LightmansDiscordIntegration/]: Error setting up the JDA.
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:407) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:331) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:297) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1828) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at io.github.lightman314.lightmansdiscord.proxy.ServerProxy.initializeJDA(ServerProxy.java:42) ~[Lightman's%20Discord%20Integration_65165ea1659f5e0027d372c5.jar%23162!/:1.20-0.2.0.2] {re:classloading}
        at io.github.lightman314.lightmansdiscord.LightmansDiscordIntegration.onConfigLoad(LightmansDiscordIntegration.java:69) ~[Lightman's%20Discord%20Integration_65165ea1659f5e0027d372c5.jar%23162!/:1.20-0.2.0.2] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42) ~[javafmllanguage-1.20.1-47.1.46.jar%23181!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:153) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:153) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:62) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.1.46.jar%23180!/:?] {}
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96) ~[forge-1.20.1-47.1.46-universal.jar%23184!/:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:162) ~[server-1.20.1-20230612.114412-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23179!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?] {}
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?] {}
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?] {}
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?] {}
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?] {}
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484) ~[?:?] {}
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478) ~[?:?] {}
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?] {}
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?] {}
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[?:?] {}
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[?:?] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?] {}
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?] {}
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar%23213!/:?] {re:classloading}
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:190) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:264) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:145) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:128) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:378) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:446) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:490) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?] {}
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] {}
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] {}
        ... 1 more
Caused by: net.dv8tion.jda.api.exceptions.ContextException
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:77) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:40) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-5.0.0-beta.13.jar%23208!/:5.0.0-beta.13] {re:classloading}
        ... 26 more

**Comment by Lightman314** [comment]
Please make sure that you are using a valid bot token, and try again a few more times, cause a `SocketTimeoutException` sounds like a connection issue with Discord, not anything that I actually have control over.

Edit: Also, please include the Minecraft Version and LDI version with all issue reports!

**Comment by Lightman314** [comment]
Closing due to inactivity...
